### ISSUE TITLE
非常好的命令行词典， 不知道 bing 有没有类似于 google 的整句翻译服务？

### ISSUE THREAD

**Issue by zw963** [lingceng/bing_dictionary#1]
这个词典非常好呀。 之前我用的都是用的本地 dict 服务 + Bash shell 写的，直接查询 google api 
整句翻译，不知道 bing 有没有提供 `整句翻译` 的功能？

例如:

``` sh
$ dict '今天吃了没'
$ dict 'How much is this notebook?'
```

**Comment by lingceng** [comment]
@zw963 多谢关注，翻译的数据是来自http://cn.bing.com/

在这里查[今天吃了没](http://cn.bing.com/dict/search?q=%E4%BB%8A%E5%A4%A9%E5%90%83%E4%BA%86%E6%B2%A1)，结果差强任意，但例句还行。
“How much is this notebook?”的翻译基本正确。
只是目前版本的dict命令查询上面的两个例子没有返回结果，需要调整下代码，兼容这类没有单词解释的输出。我会抽时间处理，你要有兴趣欢迎提交pull request给我。

google api的翻译似乎是[需要收费](https://cloud.google.com/translate/v2/getting_started)了，所以没有使用。

**Comment by lingceng** [comment]
Now this feature supported.

**Comment by zw963** [comment]
太酷了！！， 效果差点没关系，关键 bing 没有墙的问题。
有空我会帮助一起改善的, 不过这里先提一个小建议。

``` ruby
  def translate(word)
    if word && !word.empty?
      @word = CGI::escape(word)
      parse Net::HTTP.get( "cn.bing.com", "/dict/search?q=#{@word}" )
    end
  # 建议这里做网络不通的异常处理。我优先会使用 dict 查询， 这样至少
  # 在 网络不通时， 可以根据非 0 的返回值调用我本地的 dict 服务。
  rescue SocketError
    warn '连接失败！‘
    exit 1
  end
```

至于你说的 Google 翻译 API, 好像一直能用呀, 除了有时候速度差了点。

``` sh
    FROM='zh'
    TO='en'
    SENTENCE=$(echo "$*"|tr " " "+")
   result=$(curl -s --user-agent "Mozilla/5.0 (X11; Linux i686) AppleWebKit/534.34 (KHTML, like Gecko) QupZilla/1.3.1 Safari/534.34" "http://translate.google.cn/m?hl=en&sl=${FROM}&tl=${TO}&ie=UTF-8&prev=_m&q=${SENTENCE}"|sed -n 's/.*class="t0">//;s/<.*$//p')
```

**Comment by lingceng** [comment]
你提供的google翻译的脚本不是使用的api，而是抓取网页，能用，就是墙麻烦。

rescue SocketError已经加上了。
