### ISSUE TITLE
fix deprecated method `Kernel#open` warning

### ISSUE THREAD

**Issue by TorvaldsDB** [lingceng/bing_dictionary#5]
- issue detail
> warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
- issue screenshot
![image](https://user-images.githubusercontent.com/12232166/122674512-25c26400-d208-11eb-87ab-25653d30f5d3.png)
- issue resson
With the upgrade of the Ruby version, this Kernel#open has been deprecated. 
When using such an awesome gem, it's not a good UX for users to receive such a disgusting message.

**Comment by lingceng** [comment]
Thank you and fixed in version 0.1.6
